# Generated by Django 3.2.6 on 2021-08-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school_T',
            fields=[
                ('school_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=30)),
            ],
        ),
    ]
