# Generated by Django 3.2.6 on 2021-08-27 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_T',
            fields=[
                ('department_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=30)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spm.school_t')),
            ],
        ),
    ]
