# Generated by Django 3.2.6 on 2021-08-27 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spm', '0002_department_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program_T',
            fields=[
                ('program_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=30)),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spm.department_t')),
            ],
        ),
        migrations.CreateModel(
            name='Student_T',
            fields=[
                ('student_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('contact_no', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=6)),
                ('date_of_birth', models.DateTimeField()),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('year', models.IntegerField(verbose_name=4)),
                ('semseter', models.CharField(max_length=10)),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spm.department_t')),
                ('program', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spm.program_t')),
            ],
        ),
    ]
