# Generated by Django 3.2.6 on 2021-08-27 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spm', '0003_program_t_student_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_t',
            name='year',
            field=models.CharField(max_length=5),
        ),
        migrations.CreateModel(
            name='Course_T',
            fields=[
                ('course_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=25)),
                ('course_type', models.CharField(max_length=10)),
                ('No of credits', models.IntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spm.program_t')),
            ],
        ),
    ]
