# Generated by Django 3.2.6 on 2021-08-27 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spm', '0004_auto_20210828_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_t',
            name='year',
        ),
        migrations.AddField(
            model_name='student_t',
            name='Year of admission',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Pre_req_course_T',
            fields=[
                ('course_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Pre_req_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spm.course_t')),
            ],
        ),
    ]
