# Generated by Django 3.2.6 on 2021-08-27 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spm', '0005_auto_20210828_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLO_T',
            fields=[
                ('plo_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('plo_name', models.CharField(max_length=30)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spm.program_t')),
            ],
        ),
        migrations.CreateModel(
            name='CO_T',
            fields=[
                ('co_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('details', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spm.course_t')),
                ('plo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spm.plo_t')),
            ],
        ),
    ]
