# Generated by Django 3.2.6 on 2021-08-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spm', '0006_co_t_plo_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_T',
            fields=[
                ('faculty_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('contact_no', models.CharField(max_length=15)),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.CharField(max_length=6)),
                ('street', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('faculty_type', models.CharField(max_length=10)),
            ],
        ),
    ]
