# Generated by Django 3.2.6 on 2021-08-28 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spm', '0007_faculty_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='VC_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('VFaculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spm.faculty_t')),
            ],
        ),
        migrations.CreateModel(
            name='GFaculty_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=25)),
                ('join_date', models.DateTimeField()),
                ('Gfaculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spm.faculty_t')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spm.department_t')),
            ],
        ),
        migrations.CreateModel(
            name='Department_Head_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('HODFaculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spm.faculty_t')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spm.department_t')),
            ],
        ),
        migrations.CreateModel(
            name='Dean_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('DFaculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spm.faculty_t')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spm.school_t')),
            ],
        ),
    ]
